// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $analysis_userkey_ from "./routes/analysis/[userkey].tsx";
import * as $api_invitations_profileId_ from "./routes/api/invitations/[profileId].ts";
import * as $api_network_profileId_ from "./routes/api/network/[profileId].ts";
import * as $api_profile_enhanced_profileId_ from "./routes/api/profile-enhanced/[profileId].ts";
import * as $api_search_users from "./routes/api/search-users.ts";
import * as $index from "./routes/index.tsx";
import * as $InvitedUsersList from "./islands/InvitedUsersList.tsx";
import * as $NetworkVisualization from "./islands/NetworkVisualization.tsx";
import * as $ProfileAnalysis from "./islands/ProfileAnalysis.tsx";
import * as $UserSearch from "./islands/UserSearch.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/analysis/[userkey].tsx": $analysis_userkey_,
    "./routes/api/invitations/[profileId].ts": $api_invitations_profileId_,
    "./routes/api/network/[profileId].ts": $api_network_profileId_,
    "./routes/api/profile-enhanced/[profileId].ts":
      $api_profile_enhanced_profileId_,
    "./routes/api/search-users.ts": $api_search_users,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/InvitedUsersList.tsx": $InvitedUsersList,
    "./islands/NetworkVisualization.tsx": $NetworkVisualization,
    "./islands/ProfileAnalysis.tsx": $ProfileAnalysis,
    "./islands/UserSearch.tsx": $UserSearch,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
